[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
db-path = "$CARGO_HOME/advisory-dbs"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []
[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Zlib",
    "MPL-2.0",
    "BSD-3-Clause",
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["CC0-1.0"], crate = "constant_time_eq" },
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
]

[licenses.private]
ignore = false
registries = []

[bans]
allow = []
deny = []
skip = []
skip-tree = [
    "windows-sys",
    "regex-automata",
    "object",
]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = ["Fundament-Software"]
