[package]
name = "keystone"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
authors = ["Erik McClure <erikm@fundament.software>"]
description = """
Core framework for managing internal company infrastructure using couchdb and capability based security.
"""
homepage = "https://github.com/Fundament-Software/keystone"
repository = "https://github.com/Fundament-Software/keystone/tree/master/core"
readme = "README.md"
keywords = ["backend", "infrastructure", "management", "enterprise", "distributed"]
license = "Apache-2.0"

[lib]
doctest = false 

[dependencies]
async-trait = "0.1.57"
atomic-counter = "1.0"
bytes = "1.4.0"
cap-std = "2.0.0"
cap-tempfile = "2.0.0"
capnp = "0.14.9"
capnp-futures = "0.14"
capnp-import = { git = "https://github.com/Fundament-Software/capnp-import" }
capnp-rpc = "0.14"
chrono = "0.4"
color-eyre = "0.6"
couch_rs = "0.9"
dlopen = "0.1.8"
eyre = "0.6"
futures = "0.3"
hyper = { version = "0.14", features = ["full"] }
hyper-tls = "0.5"
log = { version = "0.4", features = ["kv_unstable"] }
pretty_env_logger = "0.4.0"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.18", features = ["full"] }
tokio-util = "0.7"
url = "2.3.1"

[dev-dependencies]
predicates = "2.1"
assert_fs = "1.0"

[build-dependencies]
anyhow = "1.*"
capnp-import = { git = "https://github.com/Fundament-Software/capnp-import" }
